name: oSNAKE-Runtime-Publish

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'  # Ensure Java 11 is used
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Verify Java Version (Ensure JRE is Present)
      run: java -version  # Prints JRE version to confirm availability

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
